apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 128.199.238.154/32
    - 2400:6180:0:d0::14fa:e005-2400:6180:0:d0::14fa:e005
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-ls-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip-pool
