apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 128.199.107.242/34
    - 2400:6180:0:d0::104:f005-2400:6180:0:d0::104:f005
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-ls-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-ip-pool
