apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  access-token: "ZG9wX3YxX2EyZmY3NmE0NWM1MjM1NzMyMWZhZDM0ZGIyZDIxZDFkOTQzNmJjNzUxNzFiYjljNTcxNTI4YmJlOGQ4YTJjNmY="
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: istio-system
data:
  access-token: "ZG9wX3YxX2EyZmY3NmE0NWM1MjM1NzMyMWZhZDM0ZGIyZDIxZDFkOTQzNmJjNzUxNzFiYjljNTcxNTI4YmJlOGQ4YTJjNmY="
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  access-token: "ZG9wX3YxX2EyZmY3NmE0NWM1MjM1NzMyMWZhZDM0ZGIyZDIxZDFkOTQzNmJjNzUxNzFiYjljNTcxNTI4YmJlOGQ4YTJjNmY="
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster
  namespace: istio-system
spec:
  acme:
    email: dotnetnat@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-cluster
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dualstack-domain-cert-prod
  namespace: istio-system
spec:
  secretName: dualstack-domain-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.dualstack.thaidevops.co"
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: dualstack-thaidevops-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.dualstack.thaidevops.co"
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*.dualstack.thaidevops.co"
      tls:
        mode: SIMPLE
        credentialName: dualstack-domain-cert-prod
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hubble-vs
  namespace: cilium
spec:
  gateways:
    - "istio-system/dualstack-thaidevops-gateway"
  hosts:
    - "hubble-ui.dualstack.thaidevops.co"
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: hubble-ui
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: kube-prometheus-stack
spec:
  gateways:
    - "istio-system/dualstack-thaidevops-gateway"
  hosts:
    - "grafana.dualstack.thaidevops.co"
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: kube-prometheus-stack-grafana
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: dualstack-domain-cert-prod
  namespace: istio-system
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUvekNDQStlZ0F3SUJBZ0lTQTkzVUI0cEJlTW10Yml1ajltUE5GY3pSTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlOREF4TVRJd09EVXpNakphRncweU5EQTBNVEV3T0RVek1qRmFNQ1F4SWpBZ0JnTlZCQU1NCkdTb3VaSFZoYkhOMFlXTnJMblJvWVdsa1pYWnZjSE11WTI4d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEVkUvVDY4d3NvMzZERU5QQjQ2L3R6MjNOTDl6M3BwYndtNVloYStZQzFPY2tvZ0NZZAppSXUrenV2RVUrZ3pYZUs3WVRyVG5tSGNjMWVoUC96RjE5d1NGVVYwYmVvUVZ2bFZnTTdvN0FoRGRhdmtKY0h6CmJZNGdIQmVmMCs0cUJJSlVIVGQwWElFam5HTWpmSmRIM2x3bmIvVFlBOXZZTFFKbTltQnh3b1VGeGFWRDRLLzYKMUQrSCtqckhaK2RQTmJCVnpCWmRKMlhPeWFEWUxSQnUyZDFweEZnTXJnd0EzNGlRZ3RWa0ZXQW5pZXJpMHFCMQplaUxBVlR3TDRVc1ZsbWZnd0pGV0draXppY09RNTBZZmtDK0JFNzlydmc1cnA3ZjlVTXRXaDBRNHh5S3NTVDBzCktaNVhYNUlWSTNvYVZqMmFXQUEzL0FIbkhzYVR1UHpDUVlmbkFnTUJBQUdqZ2dJYk1JSUNGekFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd0hRWURWUjBPQkJZRUZFeFYrSWw4Vnl3WkcwYzAzQXNaWCtqblFVck9NQjhHQTFVZEl3UVlNQmFBCkZCUXVzeGUzV0ZiTHJsQUpRT1lmcjUyTEZNTEdNRlVHQ0NzR0FRVUZCd0VCQkVrd1J6QWhCZ2dyQmdFRkJRY3cKQVlZVmFIUjBjRG92TDNJekxtOHViR1Z1WTNJdWIzSm5NQ0lHQ0NzR0FRVUZCekFDaGhab2RIUndPaTh2Y2pNdQphUzVzWlc1amNpNXZjbWN2TUNRR0ExVWRFUVFkTUJ1Q0dTb3VaSFZoYkhOMFlXTnJMblJvWVdsa1pYWnZjSE11ClkyOHdFd1lEVlIwZ0JBd3dDakFJQmdabmdRd0JBZ0V3Z2dFRUJnb3JCZ0VFQWRaNUFnUUNCSUgxQklIeUFQQUEKZFFCSXNPTnIycVpITkEvbGFnTDZuVERySEZJQnkxYmRMSUhadTcrck9kaUVjd0FBQVl6OUZ5b1FBQUFFQXdCRwpNRVFDSUI5S01wQVlHaVREWGVBZnlBbThnRS9mcklXb0h3bnFQOExGaUpPNklCSmpBaUFISE5rWFlmTXB4SXFJCmwrQVhUSHhmcXBKSTN5ZHFLVEo0M0dEUXpTSFlIUUIzQUhiL2lEOEt0dnVWVWNKaHpQV0h1alMwcE0yN0tkeG8KUWdxZjVtZE1XanAwQUFBQmpQMFhLbGdBQUFRREFFZ3dSZ0loQU5vRUlkQ3dwbDhqREwybDB6b0NPWjZFbExxVApCSy8wUXNBUSs5cjYwWHRrQWlFQXhDeERaTWZOcmpQeU1JYmpKR0hQTnN4eXVNd0NLVjY3czB4ZkhXTVA3YVl3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMTXdvL0VrZW1rRGI4K3pvSklWNFFoS2IwRkN3THFWZVdZM1hnSlUKV01VV1Z1RUpLMjVYRUNzQlNWUjZYRkxnMVJmOXgrOWoyejZ0Z3FnNUJYV2JRWmRCUW9CSHBRMG1UUzdPc2xMKwpLZFFkSGR1NFNLcEdJajN0QmdnUXNQaXdlWUJqSGMyMWpvNElQalI2WWVMdjZnOHNSVGFnSS9mcHBjUzlTU0JLClBzdHRObUMrZDEwcXFmVUpxL2xvMUZoMmFoRmxhbGhHSjdWWGtwTU9ZcUJpOG9DRkNoTmd3VnFLTnNIbUFXaU8KeEdYQ0taM0JnTjNlNnRhRk4rR1pCMFJwa3IzamVaRXB0M1haM1VzYUNzd0dYblltYXQ5aTVXd1hPQXEvc1VzNwo0K2RSRFlDbkcwb1MxYnZheloyN29jVVhsL1V4bEN4SnQ4SjZKdDhuQWF2cHA4WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkZqQ0NBdjZnQXdJQkFnSVJBSkVyQ0VyUERCaW5VL2JXTGlXblgxb3dEUVlKS29aSWh2Y05BUUVMQlFBdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05WQkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1qQXdPVEEwTURBd01EQXcKV2hjTk1qVXdPVEUxTVRZd01EQXdXakF5TVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5UR1YwSjNNZwpSVzVqY25sd2RERUxNQWtHQTFVRUF4TUNVak13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM3QWhVb3pQYWdsTk1QRXV5TlZaTEQrSUx4bWFaNlFvaW5YU2FxdFN1NXhVeXhyNDVyK1hYSW85Y1AKUjVRVVZUVlhqSjZvb2prWjlZSThRcWxPYnZVN3d5N2JqY0N3WFBOWk9PZnR6Mm53V2dzYnZzQ1VKQ1dIK2pkeApzeFBuSEt6aG0rL2I1RHRGVWtXV3FjRlR6alRJVXU2MXJ1MlAzbUJ3NHFWVXE3WnREcGVsUURScks5TzhadXRtCk5IejZhNHVQVnltWitEQVhYYnB5Yi91QnhhM1NobGc5RjhmbkNidnhLL2VHM01IYWNWM1VSdVBNclNYQmlMeGcKWjNWbXMvRVk5NkpjNWxQL09vaTJSNlgvRXhqcW1BbDNQNTFUK2M4QjVmV21jQmNVcjJPay81bXprNTNjVTZjRwova2lGSGFGcHJpVjF1eFBNVWdQMTdWR2hpOXNWQWdNQkFBR2pnZ0VJTUlJQkJEQU9CZ05WSFE4QkFmOEVCQU1DCkFZWXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01CTUJJR0ExVWRFd0VCL3dRSU1BWUIKQWY4Q0FRQXdIUVlEVlIwT0JCWUVGQlF1c3hlM1dGYkxybEFKUU9ZZnI1MkxGTUxHTUI4R0ExVWRJd1FZTUJhQQpGSG0wV2VaN3R1WGtBWE9BQ0lqSUdsajI2WnR1TURJR0NDc0dBUVVGQndFQkJDWXdKREFpQmdnckJnRUZCUWN3CkFvWVdhSFIwY0RvdkwzZ3hMbWt1YkdWdVkzSXViM0puTHpBbkJnTlZIUjhFSURBZU1CeWdHcUFZaGhab2RIUncKT2k4dmVERXVZeTVzWlc1amNpNXZjbWN2TUNJR0ExVWRJQVFiTUJrd0NBWUdaNEVNQVFJQk1BMEdDeXNHQVFRQgpndDhUQVFFQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ0Z5azVIUHFQM2hVU0Z2TlZuZUxLWVk2MTFUUjZXClBUTmxjbFF0Z2FEcXcrMzRJTDlmekxkd0FMZHVPL1plbE43a0lKK203NHV5QStlaXRSWThrYzYwN1RrQzUzd2wKaWtmbVpXNC9SdlRaOE02VUsrNVV6aEs4akNkTHVNR1lMNkt2elhHUlNnaTN5TGdqZXdRdENQa0lWejZEMlFRegpDa2NoZUFtQ0o4TXF5SnU1emx6eVpNakF2bm5BVDQ1dFJBeGVrcnN1OTRzUTRlZ2RSQ25iV1NEdFk3a2grQkltCmxKTlhvQjFsQk1FS0lxNFFEVU9Yb1JnZmZ1RGdoamUxV3JHOU1MK0hiaXNxL3lGT0d3WEQ5UmlYOEY2c3c2VzQKYXZBdXZEc3p1ZTVMM3N6ODVLK0VDNFkvd0ZWRE52Wm80VFlYYW82WjBmK2xRS2MwdDhEUVl6azFPWFZ1OHJwMgp5Sk1DNmFsTGJCZk9EQUxadllIN243ZG8xQVpsczRJOWQxUDRqbmtEclFveEIzVXFROWhWbDNMRUtRNzN4RjFPCnlLNUdoRERYOG9WZkdLRjV1K2RlY0lzSDRZYVR3N21QM0dGeEpTcXYzKzBsVUZKb2k1TGM1ZGExNDlwOTBJZHMKaENFeHJvTDErN21yeUlrWFBlRk01VGdPOXIwcnZaYUJGT3ZWMnowZ3AzNVowK0w0V1BsYnVFak4vbHhQRmluKwpIbFVqcjhnUnNJM3FmSk9RRnkvOXJLSUpSMFkvOE9td3QvOG9UV2d5MW1kZUhtbWprN2oxbllzdkM5SlNRNlp2Ck1sZGxUVEtCM3poVGhWMStYV1lwNnJqZDVKVzF6YlZXRWtMTnhFN0dKVGhFVUczc3pnQlZHUDdwU1dUVVRzcVgKbkxSYndIT29xN2hId2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGWURDQ0JFaWdBd0lCQWdJUVFBRjNJVGZVNlVLNDduYXFQR1FLdHpBTkJna3Foa2lHOXcwQkFRc0ZBREEvCk1TUXdJZ1lEVlFRS0V4dEVhV2RwZEdGc0lGTnBaMjVoZEhWeVpTQlVjblZ6ZENCRGJ5NHhGekFWQmdOVkJBTVQKRGtSVFZDQlNiMjkwSUVOQklGZ3pNQjRYRFRJeE1ERXlNREU1TVRRd00xb1hEVEkwTURrek1ERTRNVFF3TTFvdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05WQkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3Z2dJaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUN0NkNSejlCUTM4NXVlSzFjb0hJZSszTGZmT0pDTWJqem1WNkI0OTNYQwpvdjcxYW03MkFFOG8yOTVvaG14RWs3YXhZLzBVRW11L0g5THFNWnNoZnRFelBMcEk5ZDE1MzdPNC94THhJWnBMCndZcUdjV2xLWm1ac2ozNDhjTCt0S1NJRzgrVEE1b0N1NGt1UHQ1bCtsQU9mMDBlWGZKbElJMVBvT0s1UENtK0QKTHRGSlY0eUFkTGJhTDlBNGpYc0RjQ0ViZGZJd1BQcVBydDNhWTZ2ckZrL0NqaEZMZnM4TDZQKzFkeTcwc250Swo0RXdTSlF4d2pRTXBvT0ZUSk93VDJlNFp2eEN6U293L2lhTmhVZDZzaHdlVTlHTng3QzdpYjF1WWdlR0pYRFI1CmJIYnZPNUJpZWViYnBKb3ZKc1hRRU9FTzN0a1FqaGI3dC9lbzk4ZmxBZ2VZanpZSWxlZmlONVlOTm5XZSt3NXkKc1IyYnZBUDVTUVhZZ2QwRnRDcldRZW1zQVhhVkNnL1kzOVc5RWg4MUx5Z1hiTktZd2FnSlpIZHVSemU2enF4WgpYbWlkZjNMV2ljVUdRU2srV1Q3ZEp2VWt5UkduV3FOTVFCOUdvWm0xcHpwUmJvWTdubjF5cHhJRmVGbnRQbEY0CkZRc0RqNDNRTHdXeVBudEtIRXR6QlJMOHh1cmdVQk44UTVOMHM4cDA1NDRmQVFqUU1OUmJjVGEwQjdyQk1EQmMKU0xlQ081aW1mV0NLb3FNcGdzeTZ2WU1FRzZLREEwR2gxZ1h4RzhLMjhLaDhoanRHcUVncWlOeDJtbmEvSDJxbApQUm1QNnpqelpON0lLdzBLS1AvMzIrSVZRdFFpMENkZDRYbitHT2R3aUsxTzV0bUxPc2JkSjFGdS83eGs5VE5EClR3SURBUUFCbzRJQlJqQ0NBVUl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVkhROEJBZjhFQkFNQ0FRWXcKU3dZSUt3WUJCUVVIQVFFRVB6QTlNRHNHQ0NzR0FRVUZCekFDaGk5b2RIUndPaTh2WVhCd2N5NXBaR1Z1ZEhKMQpjM1F1WTI5dEwzSnZiM1J6TDJSemRISnZiM1JqWVhnekxuQTNZekFmQmdOVkhTTUVHREFXZ0JURXA3R2tleXh4Cit0dmhTNUIxLzhRVllJV0pFREJVQmdOVkhTQUVUVEJMTUFnR0JtZUJEQUVDQVRBL0Jnc3JCZ0VFQVlMZkV3RUIKQVRBd01DNEdDQ3NHQVFVRkJ3SUJGaUpvZEhSd09pOHZZM0J6TG5KdmIzUXRlREV1YkdWMGMyVnVZM0o1Y0hRdQpiM0puTUR3R0ExVWRId1ExTURNd01hQXZvQzJHSzJoMGRIQTZMeTlqY213dWFXUmxiblJ5ZFhOMExtTnZiUzlFClUxUlNUMDlVUTBGWU0wTlNUQzVqY213d0hRWURWUjBPQkJZRUZIbTBXZVo3dHVYa0FYT0FDSWpJR2xqMjZadHUKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBS2N3QnNsbTcvRGxMUXJ0Mk01MW9HclMrbzQ0Ky95UW9ERlZEQwo1V3hDdTIrYjlMUlB3a1NJQ0hYTTZ3ZWJGR0p1ZU43c0o3bzVYUFdpb1c1V2xIQVFVN0c3NUsvUW9zTXJBZFNXCjlNVWdOVFA1MkdFMjRIR050TGkxcW9KRmxjRHlxU01vNTlhaHkyY0kycUJETEtvYmt4L0ozdldyYVYwVDlWdUcKV0NMS1RWWGtjR2R0d2xmRlJqbEJ6NHBZZzFodG1mNVg2RFlPOEE0anF2MklsOURqWEE2VVNiVzFGelhTTHI5TwpoZThZNElXUzZ3WTdiQ2tqQ1dEY1JRSk1FaGc3NmZzTzN0eEUrRmlZcnVxOVJVV2hpRjFteXY0UTZXK0N5QkZDCkRmdnA3T09HQU42ZEVPTTQrcVI5c2Rqb1NZS0VCcHNyNkd0UEFRdzRkeTc1M2VjNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMVJQMCt2TUxLTitneERUd2VPdjdjOXR6Uy9jOTZhVzhKdVdJV3ZtQXRUbkpLSUFtCkhZaUx2czdyeEZQb00xM2l1MkU2MDU1aDNITlhvVC84eGRmY0VoVkZkRzNxRUZiNVZZRE82T3dJUTNXcjVDWEIKODIyT0lCd1huOVB1S2dTQ1ZCMDNkRnlCSTV4akkzeVhSOTVjSjIvMDJBUGIyQzBDWnZaZ2NjS0ZCY1dsUStDdgordFEvaC9vNngyZm5Ueld3VmN3V1hTZGx6c21nMkMwUWJ0bmRhY1JZREs0TUFOK0lrSUxWWkJWZ0o0bnE0dEtnCmRYb2l3RlU4QytGTEZaWm40TUNSVmhwSXM0bkRrT2RHSDVBdmdSTy9hNzRPYTZlMy9WRExWb2RFT01jaXJFazkKTENtZVYxK1NGU042R2xZOW1sZ0FOL3dCNXg3R2s3ajh3a0dINXdJREFRQUJBb0lCQUFqMUROQmIxVFZEcVZ0MgpLa0c3RWRmOStxdlAyZTl2Z3loVGI5YjdOQmpxTS9XYTVYOUtWUzJSUDBJQ2tQbFAwZzgwZUNlYk9kdnRrVnA2CitTSkwvN2xXNFpPU1owdUdqSGEyc253Q0tCckY0SkwzcjE2UFZYRXVIU1FmNFp3c2tsbjgzRzdzMEpUeHB3MC8KMkpBeDNjZmVvZmxPdURndk5ER2wyOG9NZGxFV3VUODl5TGdRRkdITEJtdEJxUlNUcldPSWdOMmV6WkNPMkEwVgo4RWxnaURNbTk2dGJUYy9iWEF4VnlQMndKVTZEVW1LU29SWk1Xck5MRUxGRFJCRXpMRTBwemcwU1Qvc2xnOWE5CjBVc1RJNG5GbWUyckFPRW9JckcyOXJVZlJyNmcrWk9sMDQwNU5OdFZSMk90SGRXamZIWXpJVWZxUnZHUDh3Uk4KS25IMW1Fa0NnWUVBOTYwdkxXbzN3alV1aHhESHQxaS93TW1IUWtoNWxCaHZEMEJTUVg5K0RNMEk2MVhSUXk3RApZM1ZqL0MzZ1lyL29aTkcyVzU1d3dTN0lzdnF4S2hXdXk3ZS8ycE5ET1ozYU9DOXBPRUk0enpUcXRRTC9sRjF0CmNwK3YxUHlLN3hYdWx3cGw1RnpWMC9XOGdKbWxRU0MwcFNKelFZWE9LZ3dYaXJJN3E4bDU2a01DZ1lFQTNEMGQKSGdtZFNOV1hqWmJXeTA1akt5OHJ5NTBHdW5MQzlOY2lzZ0hHS0N5UFRhWHovOURMQ0d2aW10RXdLSTFrVEMrdQpNQ0FJUkNVaGZadDFzbUVVS254QVFLczBRVGhNclVZRStUNzJUd1cyWng3STFVcEErYVgwTG1BZXVkOVJVeXUvCkxvYVhoZkRSTHZGZE1CUE9NRlQrS1M0dGs5b0VIUm13dWNhdzY0MENnWUJEa21SRXA2Myt0ak96ZGNpSEpSZHIKcVkvVmJhQjkzd3l0eElhc2gvUUQyZ3lNNkNUbmgyS1hSL2UzWFd6U2hEa0xDSXdRQXZJUVFvdFBDVVk4alIzYgpSbzU1TzZRam5BVmxQc29lSnpNSWxROVR3elduYkxYbmg5bVk2aTJkZlFaUy91czltblpjRmJjUC90c3ZJWlVuCldIYkpjWkFGdUxiVGlEenZhVkJ4c1FLQmdRQ2tnRVZhWlVZRTIvMGFOZHR6K2JYYTBKMyt0T2dNcGFGMjdhWXQKbldPY0tFUlZkQ28vSG40NGFSVFdISC9ER25FYTh0WkJmZnVPb3NsVUg2VVd1cW9zWGFoRVpWeGZocVRIRzdDbApWdUQwLzBoUjE4MmNlcHp6bTRBNmozTUQxSWpTL2E4TUdsM2RIcFd3WVhvQWFocXRRUjZpTmFxM2I3VjQ0dko4Cm9Lc1BGUUtCZ0NNOGh2eUNyV25SN3dncXJNWXZXK2VadU8zSVVoOHBsZGZtdnNQUlBCQjYxTVZzUkx3Y0YycEEKYUJEbnFhUnpUYnBJaXlvck9TUWhueFhYRFozSitOUUlTR25xTUdtSXB4VVZiU01IYXZyL09LcGp4TVRpbE93VQpUeDRKM2N4eCt0QktKNTZrdFhzdmxlWUZBZExMd0QyZmV4SnNQbHVpVFYraXpIVFMzaDVOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
type: kubernetes.io/tls
